# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ba5351c83273b32d4cb6fc8f34eb4524fd85d48fb3fa78c9028c922be2af8119ebd3c7a3cc8cf6af59c4c07e27ea7e5638c15a695fe58d60ed47420288b7459
  stripe_publishable_key: pk_test_7CMIjTOkDl8S6fkOImYJ8Qz5
  stripe_secret_key: sk_test_FQN03AnepMDNcZaFFduIsVJS
  stripe_connect_client_id: ca_5qamk5Dt98nk4LcYpzrgDgYk6ARmn4rw
  pusher_app_id: '133847'
  pusher_key: efb3250cf7fd30c78d49
  pusher_secret: 2d9da406190b5c9dd3ed

test:
  secret_key_base: 531ebb09fd8588d924c2a9f54694e7596df5a7f68e4c097efc2029bd07997d35162a584fa1f009e1a8f934e4868e99e0fe0508e3e18dda89c109566cb9b2a85d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_publishable_key: pk_test_7CMIjTOkDl8S6fkOImYJ8Qz5
  stripe_secret_key: sk_test_FQN03AnepMDNcZaFFduIsVJS
  stripe_connect_client_id: ca_5qamk5Dt98nk4LcYpzrgDgYk6ARmn4rw
